#!/bin/sh
PKGREPO="https://ilovetrees242.github.io/DevHelp/Website/Packages/"
case $1 in
	unveil)
		case $2 in
			$2)
				echo "Checking if the package $2 exists..."
				wget "$PKGREPO$2.tar.gz" &> /dev/null 
				case $? in
					8)
						echo "ERROR: Package not found!"
					;;
					0)
					echo "Package found!"
					echo "Installing $2 in"
					for i in 1 2 3 4 5 ; do
						echo "${i}..."
						sleep 1
					done
					wget $PKGREPO/$2.tar.gz
					tar xf $2.tar.gz
					pushd $2
					./LFSBUILD build
					popd 
					rm -rf $2 $2.tar.gz*
					;;
				esac
			;;
			*)
				echo "You did not specify the package name!"
			;;
		esac
	;;
	veil)
		case $2 in
			$2)
				echo "Checking if the package $2 exists..."
				wget "$PKGREPO$2.tar.gz" &> /dev/null
				case $? in
					8)
						echo "Package does not exist!"
					;;
					0)
						echo "Package found! Uninstalling in..."
						for i in 1 2 3 4 5 ; do
							echo "${i}..."
							sleep 1
						done
						wget $PKGREPO/$2.tar.gz
						tar xf $2.tar.gz
						pushd $2
						./LFSBUILD uninstall
						popd
						rm -rf $2 $2.tar.gz*
						;;
				esac
			;;
			*)
				echo "Invalid option. Exiting."
			;;
		esac
	;;
	expand)
		e
	;;
	strengthen)
		e
	;;
	help)
		e
	;;
	*)
		echo "$0 Usage: $0 <OPTIONS> <COMMAND>"
		echo "$0 <OPTIONS> unveil|veil [PACKAGE]"
		echo "$0 Options: --verbose: Displays verbose output
			         --quiet  : Displays quiet output, not too detailed.
				 --documentation: Enables documentation (this might install extra dependencies)
				 --test   : Enables test harnesses
		"
		echo "$0 unveil: Installs a package from source."
		echo "$0 veil  : Uninstalls a package installed on the system"
		echo "$0 expand: Syncs the package repository so that it finds newer versions."
		echo "$0 strengthen: Updates all packages installed on the system"
		echo "$0 help: Displays this output"
	;;
esac
